networks:
  muchtodo-net:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  app_logs:
    driver: local

services:
  muchtodo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muchtodo-app
    ports:
      - "8082:8080"
    environment:
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/?authSource=admin
      DB_NAME: ${DB_NAME}
    depends_on:
      - mongodb
    networks:
      - muchtodo-net
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - muchtodo-net

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_SERVER}
    depends_on:
      - mongodb
    networks:
      - muchtodo-net


