apiVersion: v1
kind: Service
metadata:
  name: muchtodo-service
  namespace: muchtodo
spec:
  selector:
    app: muchtodo-app
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080